services:
    ubuntu:
        public: true
        container_name: tzchz
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        ports:
            - 6080:6080
            - 20
            - 21
            - 990
            - 40000:50000
        environment: 
            - VNC_PASSWD=god123
            - GEOMETRY=1280x768
            - TZ=Asia/Ho_Chi_Minh
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 1000m
          memory: 3072Mi
          storage:
            size: 5Gi
            class: standard
